### ISSUE TITLE
TODO for next releases

### ISSUE THREAD

**Issue by filimonov** [filimonov/chc#1]
- [ ] session keep-alive pings
- [ ]  query kill confirmation (currently it always return that it was killed)
- [x] INTO OUTFILE - should write file only if select was successful.
- [x] binary mode bugfix (FORMAT Native)
- [ ] multiquery support
- [ ]  password from ENV, or from user input
- [ ] custom prompt
- [ ] http compression
- [ ] better format for progress bar
- [ ] config file support
- [ ] test https
- [ ] attaching files
- [ ] ability to switch method of collecting progress info
- [ ] readonly mode.
- [ ] better intro message (MySQL like)
- [ ] session reset
- [ ] tty tests with expect
- [ ] better prompt (prompt_toolkit alike, https://github.com/c-bata/go-prompt ? )

**Comment by filimonov** [comment]
to multiline mode: skip semicolons in commens

**Comment by filimonov** [comment]
switch to https://github.com/c-bata/go-prompt ?
